### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte

### ISSUE THREAD

**Issue by zengateway** [akmalovaa/mikroseclist#2]
Hello, i have an error:

```
09.08.24 14:06:19 INFO Mikrotik firewall address list sync started

09.08.24 14:06:19 INFO Fetch firewall address list: block

09.08.24 14:06:19 INFO Success connection to host: 192.168.101.1

09.08.24 14:06:19 INFO Save crowdsec blocklist to file: blocklist.txt

09.08.24 14:06:19 INFO Starting synchronization, total count crowdsec addresses 43567

09.08.24 14:06:19 INFO Start upload block list addresses via file

Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "/srv/mikroseclist/main.py", line 113, in <module>

    sync_addres_list()

  File "/srv/mikroseclist/main.py", line 88, in sync_addres_list

    upload_blocklist_file(crowdsec_block_list)

  File "/srv/mikroseclist/main.py", line 51, in upload_blocklist_file

    mikrotik.remove_file(settings.blocklist_filename)

  File "/srv/mikroseclist/mikrotik_client.py", line 113, in remove_file

    for file in mikrotik_files.get():

                ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/routeros_api/resource.py", line 7, in get

    return self.call('print', {}, kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/routeros_api/resource.py", line 39, in call

    additional_queries=additional_queries).get()

                                           ^^^^^

  File "/usr/local/lib/python3.11/site-packages/routeros_api/resource.py", line 86, in get

    return response.map(self.transform_dictionary)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/routeros_api/api_communicator/base.py", line 161, in map

    result = type(self)(map(function, self), command=self.command)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/routeros_api/api_communicator/base.py", line 143, in __init__

    super(AsynchronousResponse, self).__init__(*args, **kwargs)

  File "/usr/local/lib/python3.11/site-packages/routeros_api/resource.py", line 89, in transform_dictionary

    return dict(self.transform_item(item) for item in row.items())

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/routeros_api/resource.py", line 89, in <genexpr>

    return dict(self.transform_item(item) for item in row.items())

                ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/routeros_api/resource.py", line 93, in transform_item

    return (key, self.structure[key].get_python_value(value))

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/routeros_api/api_structure.py", line 31, in get_python_value

    return bytes.decode()

           ^^^^^^^^^^^^^^

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
```

can you help me please?

**Comment by akmalovaa** [comment]
exploring

**Comment by akmalovaa** [comment]
in what format are the lines, output?
http://crowdsec-blocklist:41412/security/blocklist?ipv4only

**Comment by zengateway** [comment]
mikrotik

10 авг. 2024 г., в 02:52, Akmalov Artur ***@***.***> написал(а):﻿
in what format are the lines, output?
http://crowdsec-blocklist:41412/security/blocklist?ipv4only

**Comment by zengateway** [comment]
> in what format are the lines, output? http://crowdsec-blocklist:41412/security/blocklist?ipv4only

this is first few lines:
```
/ip firewall address-list remove [find list=CrowdSec]
/ip firewall address-list add list=CrowdSec address=1.10.143.17 comment="crowdsecurity/ssh-bf for 75h12m53.824422891s"
/ip firewall address-list add list=CrowdSec address=1.116.136.219 comment="crowdsecurity/ssh-slow-bf for 157h24m56.81701527s"
/ip firewall address-list add list=CrowdSec address=1.116.238.156 comment="crowdsecurity/http-probing for 132h35m51.821204631s"
/ip firewall address-list add list=CrowdSec address=1.116.38.108 comment="crowdsecurity/ssh-slow-bf for 153h24m56.818067192s"
/ip firewall address-list add list=CrowdSec address=1.116.45.166 comment="crowdsecurity/ssh-slow-bf for 84h8m48.824000074s"
/ip firewall address-list add list=CrowdSec address=1.117.22.30 comment="crowdsecurity/http-bad-user-agent for 115h11m44.822570079s"
```

**Comment by zengateway** [comment]
Router OS v7.15.3 is latest
Here is logs from mikrotik:
```
 08:48:21 system,info,account user crowdsec logged in from 192.168.101.107 via api
 08:48:21 system,info,account user crowdsec logged out from 192.168.101.107 via api
 08:48:22 system,info,account user crowdsec logged in from 192.168.101.107 via api
 08:48:22 system,info,account user crowdsec logged out from 192.168.101.107 via api
 08:48:23 system,info,account user crowdsec logged in from 192.168.101.107 via api
 08:48:23 system,info,account user crowdsec logged out from 192.168.101.107 via api
 08:48:24 system,info,account user crowdsec logged in from 192.168.101.107 via api
 08:48:24 system,info,account user crowdsec logged out from 192.168.101.107 via api
 08:48:29 system,info,account user crowdsec logged in from 192.168.101.107 via api
 08:48:29 system,info,account user crowdsec logged out from 192.168.101.107 via api
 08:48:29 system,info,account user crowdsec logged in from 192.168.101.107 via api
 08:48:29 system,info,account user crowdsec logged out from 192.168.101.107 via api
 08:48:37 system,info,account user crowdsec logged in from 192.168.101.107 via api
 08:48:37 system,info,account user crowdsec logged out from 192.168.101.107 via api
 08:48:37 system,info,account user crowdsec logged in from 192.168.101.107 via api
 08:48:37 system,info,account user crowdsec logged out from 192.168.101.107 via api
```

**Comment by akmalovaa** [comment]
need change crowdsec-blocklist config 
```
blocklists:
  - format: plain_text
```

According to the documentation, BlackList Mirror supports various output formats:

- **plain_text:** Just IP addresses, each on a separate line
- **mikrotik:** Output lines in the format of RouterOS
/ip firewall address-list add list={list_name} address={ip} comment="{scenario} for {duration}
- **F5:** Output lines in f5 command format: {ip|range},{netmask},bl,{scenario}

I used earlier output format of `mikrotik`
This setting will help you receive a response from the http server in a pre-prepared form of commands for the router. 

Add a script to the scheduler:
```
/tool fetch url="http://YOUR_IP:41412/security/blocklist?ipv4only" dst-path=block_list.rsc;
:import block_list.rsc 
```

The list of IP addresses at that moment was ~ 30,000, a delay was added every 30 minutes according to the schedule, the router deleted all IP addresses and added all > 30,000 addresses again, even if only 1 address changed.

This is a working solution, but it is advisable to make a revision that will only perform synchronization, and not permanently delete and add the entire list. 

To do this, I will use another separate service - MikroSecList + output `plain_text`. Which will allow you to easily update the list of locks

**Comment by akmalovaa** [comment]
I hope I explained it clearly, sorry, my English is bad


finally:

- If the **output format mikrotik** is used, then the script is enough (not need service: `mikroseclist`)
```
/tool fetch url="http://YOUR_IP:41412/security/blocklist?ipv4only" dst-path=block_list.rsc;
:import block_list.rsc 
```

- If you need to use the service `mikroseclist`, then change the **output format plain_text**

**Comment by zengateway** [comment]
> I hope I explained it clearly, sorry, my English is bad
> 
> finally:
> 
>     * If the **output format mikrotik** is used, then the script is enough (not need service: `mikroseclist`)
> 
> 
> ```
> /tool fetch url="http://YOUR_IP:41412/security/blocklist?ipv4only" dst-path=block_list.rsc;
> :import block_list.rsc 
> ```
> 
>     * If you need to use the service `mikroseclist`, then change the **output format plain_text**

Понятно, да мой английский еще хуже, это я извиняюсь. Вообщем изменил на plain_test обратно, вывод стал только ip адреса, но в логах mikroseclist все таже ошибка

**Comment by akmalovaa** [comment]
Странно, посмотрю как время будет, можно мне в телеграм написать, думаю быстрее проверим решим

**Comment by zengateway** [comment]
For those who encounter this problem you need to delete files from Mikrotik - Files, run mikriseclist and then you can put files back, at least it works for me.
Problem solved, thanks to Artur!
